services:
  pgdatabase:
    image: postgres:13
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=NYC_green_taxi
    volumes:
      - "taxi_etl:/var/lib/postgresql/data:rw"
    ports:
      - "5432:5432"    
    networks:
      - airflow
volumes:
  taxi_etl:
networks:
  airflow:
    external:
      name: airflow_default  
